apps/mybnb/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import preview_home, search

app_name = "mybnb"
urlpatterns = [
    path("", RedirectView.as_view(pattern_name="mybnb:search")),
    path("search/", search, name="search"),
    path("preview_home/<str:doc_id>", preview_home, name="preview"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.mybnb.urls")),
]

apps/mybnb/models.py
from django.db import models
from model_utils.models import UUIDModel


class HomeManager(models.Manager):
    def get_index_objects(self):
        """Objects formatted for indexing"""
        return [h.dict() for h in self.get_queryset()]

    def get_filter_attributes(self):
        """A dict of filterable attributes"""
        qs = self.get_queryset()
        return {
            "countries": list(set(qs.values_list("country", flat=True))),
            "cities": list(set(qs.values_list("city", flat=True))),
        }


class Home(UUIDModel):
    address = models.CharField(max_length=300)
    price = models.DecimalField(decimal_places=2, max_digits=7, default=100)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    image_url = models.CharField(max_length=500, default="")

    objects = HomeManager()

    def dict(self):
        return {
            "id": str(self.id),
            "address": self.address,
            "price": float(self.price),
            "city": self.city,
            "country": self.country,
            "image_url": self.image_url,
        }

apps/mybnb/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from apps.mybnb.business_logic import get_opt_params
from apps.mybnb.models import Home
from apps.mybnb.search_index import search_index


@require_http_methods(["POST", "GET"])
def search(request):

    context, query_dict = {}, {}
    # use template partial for htmx requests
    template_name = "mybnb/search.html"
    if request.htmx:
        template_name = "mybnb/htmx/gallery.html"
    else:
        context.update(Home.objects.get_filter_attributes())

    # fetch and format search query parameters
    query_dict = request.GET if request.method == "GET" else request.POST
    opt_params = get_opt_params(query_dict)
    query = query_dict.get("query", None)

    # fetch results from the index and add them to the context
    results = search_index.search(query=query, opt_params=opt_params)
    next_offset = opt_params.get("offset", 0) + 20  # similar to pagination,
    context.update(
        {
            "homes": results["hits"],
            "total": results["nbHits"],
            "processing_time": results["processingTimeMs"],
            "next_offset": next_offset,
        }
    )
    return render(request, template_name, context)


def preview_home(request, doc_id):
    home = search_index.get_document(doc_id)
    template_name = "mybnb/htmx/preview.html"
    return render(request, template_name, {"home": home})

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as language_code %}

<html lang="{{ language_code }}">

    <head>
        <title>{% spaceless %}{% block title %}{% endblock %}{% endspaceless %} </title>
        <meta charset="UTF-8">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'css/site.css' %}"/>

        {% block extra_css %}{% endblock %}
        {% block head_js %}{% endblock %}

        <!--Dont use this in production -->
        <script src="https://cdn.tailwindcss.com"></script>

        <!--In production save these to your static files -->
        <script src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
        <script src="https://unpkg.com/hyperscript.org@0.9.5" defer></script>
        <script src="{% static 'js/htmx/htmx.min.js' %}" defer></script>

    </head>

    {# include csrf token in header of every request #}
    <body id="id-body" class="bg-slate-100"  hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

        {% block content %}

        {% endblock %}


        {% block footer_js %}

        {% endblock %}

    </body>
</html>

templates/common/django_tables2.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
    <div class="w-full flex flex-col">
        <div class="shadow overflow-hidden border dark:border border-gray-200 sm:rounded-lg max-h-[600px] overflow-y-auto">
            {% block table %}
                <table class="min-w-full divide-y divide-gray-200" {% render_attrs table.attrs %}>
                    {% block table.thead %}
                        {% if table.show_header %}
                            <thead class="bg-gray-50 dark:bg-gray-700 sm:rounded-lg" {{ table.attrs.thead.as_html }}>
                                <tr >
                                    {% for column in table.columns %}
                                        <th class="sticky top-0 px-2 py-1 sm:px-6 sm:py-3 text-left text-xs font-medium text-gray-600 dark:text-gray-300 bg-gray-50 dark:bg-slate-600 uppercase tracking-wider z-20" {{ column.attrs.th.as_html }}>
                                            {% if column.orderable %}
						<a hx-get="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}"
                            			   hx-target="#tableContainer" hx-swap="outerHTML">{{ column.header }}</a>
                                            {% else %}
                                                {{ column.header }}
                                            {% endif %}
                                        </th>
                                    {% endfor %}
                                </tr>
                            </thead>
                        {% endif %}
                    {% endblock table.thead %}
                    {% block table.tbody %}
                        <tbody class="text-sm font-light bg-white dark:bg-gray-700 sm:rounded-lg" {{ table.attrs.tbody.as_html }}>
                            {% for row in table.paginated_rows %}
                                {% block table.tbody.row %}
                                    <tr class="text-sm text-gray-600 dark:text-slate-200 hover:bg-gray-100" {{ row.attrs.as_html }}>
                                        {% for column, cell in row.items %}
                                            <td class="py-3 px-6" {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                                        {% endfor %}
                                    </tr>
                                {% endblock table.tbody.row %}
                            {% empty %}
                                {% if table.empty_text %}
                                    {% block table.tbody.empty_text %}
                                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                                    {% endblock table.tbody.empty_text %}
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    {% endblock table.tbody %}
                    {% block table.tfoot %}
                        {% if table.has_footer %}
                            <tfoot {{ table.attrs.tfoot.as_html }}>
                                <tr>
                                    {% for column in table.columns %}
                                        <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                                    {% endfor %}
                                </tr>
                            </tfoot>
                        {% endif %}
                    {% endblock table.tfoot %}
                </table>
            {% endblock table %}
        </div>
        <div>
            {% block pagination %}
                {% if table.page and table.paginator.num_pages > 1 %}
                    <ul class="flex space-x-3 mt-2 py-2 justify-center items-end">
                        {% if table.page.has_previous %}
                            {% block pagination.previous %}
                                <li>
                                    <button hx-get="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" hx-target="#tableContainer" hx-swap="outerHTML">
                                        &larr;
                                    </button>
                                </li>
                            {% endblock pagination.previous %}
                        {% endif %}
                        {% if table.page.has_previous or table.page.has_next %}
                            {% block pagination.range %}
                                {% for p in table.page|table_page_range:table.paginator %}
                                    <li {% if p == table.page.number %}{% endif %}>
                                        {% if p == '...' %}
                                            <button href="#">{{ p }}</button>
                                        {% else %}
                                            <button {% if p == table.page.number %}class="underline decoration-blue-600" {% else %}class="" {% endif %} hx-get="{% querystring table.prefixed_page_field=p %}" hx-target="#tableContainer" hx-swap="outerHTML">
                                                {{ p }}
                                            </button>
                                        {% endif %}
                                    </li>
                                {% endfor %}
                            {% endblock pagination.range %}
                        {% endif %}
                        {% if table.page.has_next %}
                            {% block pagination.next %}
                                <li>
                                    <button class="text-blue-600" hx-get="{% querystring table.prefixed_page_field=table.page.next_page_number %}" hx-target="#tableContainer" hx-swap="outerHTML">
                                        &rarr;
                                    </button>
                                </li>
                            {% endblock pagination.next %}
                        {% endif %}
                    </ul>
                {% endif %}
            {% endblock pagination %}
        </div>
    </div>
{% endblock table-wrapper %}

templates/mybnb/components/_filter_checkbox.html
<div class="relative flex items-start py-2 px-2">
    <div class="mr-3 flex items-center h-5">
        <input id="id_{{ name|slugify }}" name="{{ prefix }}" value="{{ name }}"
            type="checkbox"
            class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
    </div>
    <div class="min-w-0 flex-1 text-sm">
        <label for="{{ name|slugify }}" class="font-medium text-gray-700 select-none">{{ name }}</label>
    </div>
</div>

templates/mybnb/components/filters.html
<div id="filters" class="relative"
    x-data="{open: false }">
    <div>
        <button type="button" class="group inline-flex items-center px-2 py-1.5 border border-gray-300 dark:border-gray-100 shadow
            text-xs font-medium rounded text-gray-800 text-sky-800 dark:text-white bg-white dark:bg-gray-600 hover:bg-gray-50
            dark:hover:bg-gray-800"
            aria-expanded="false"
            :class="open ? 'text-gray-900' : 'text-gray-500'" @click="open = !open">
            <svg xmlns="http://www.w3.org/2000/svg"  class="h-5 w-5 mr-1" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd"
                    d="M3 3a1 1 0 011-1h12a1 1 0 011 1v3a1 1 0 01-.293.707L12 11.414V15a1 1 0 01-.293.707l-2 2A1 1 0 018 17v-5.586L3.293 6.707A1 1 0 013 6V3z"
                    clip-rule="evenodd"/>
            </svg>
            <span>Filters</span>
        </button>
    </div>
    <div
        x-transition:enter="transition ease-out duration-300"
        x-transition:enter-start="opacity-0 translate-y-1"
        x-transition:enter-end="opacity-100 translate-y-0"
        x-transition:leave="transition ease-in duration-300"
        x-transition:leave-start="opacity-100 translate-y-0"
        x-transition:leave-end="opacity-0 translate-y-1"
        x-show="open" x-cloak
        class="absolute z-40 left-1/2 transform -translate-x-2/3 mt-3 px-2 w-64 max-w-md sm:px-0">
        <div
            @click.away="open = false"
            class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden"  >
            <div class="p-1 bg-gray-50">
                <div class="-m-3 p-3 rounded-md hover:bg-gray-100 transition ease-in-out duration-150">
                    <span class="p-2 block text-sm text-gray-500"> Countries </span>
                </div>
            </div>
            <div class="border-t border-b border-gray-200 divide-y divide-gray-200 bg-white h-56 overflow-y-auto">
                {% for country in countries|slice:"1:10" %}
                    {% include "mybnb/components/_filter_checkbox.html" with prefix='country' name=country %}
                {% endfor %}
            </div>
            <div class="p-1 bg-gray-50">
                <div class="-m-3 p-3 flex justify-end rounded-md hover:bg-gray-100 transition ease-in-out duration-150">
                    <button type="submit" class="group inline-flex items-center px-2 py-0.5 border border-gray-300 dark:border-gray-100 shadow
                        text-xs font-medium rounded text-gray-800 text-sky-800 dark:text-white bg-white dark:bg-gray-600 hover:bg-sky-500 hover:text-white
                        dark:hover:bg-gray-800"
                        aria-expanded="false"
                        :class="open ? 'text-gray-900' : 'text-gray-500'" @click="open = false">
                        <span>Apply</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/mybnb/components/header.html
<div class="flex items-center space-x-3" x-data="{show_actions: false}">
    <h2 class="font-semibold text-2xl text-gray-700 flex items-center" @click="show_actions = !show_actions">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-10 w-10 p-1 bg-sky-200 rounded-full mr-2 shadow"
            fill="none" viewBox="0 0 24 24"
            stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round"
                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/>
        </svg>
        <span>MY.BNB</span>
    </h2>

</div>

templates/mybnb/components/offset.html
<input type="hidden" id="offsetField" name="next_offset" hx-swap-oob="true" value="{{ next_offset }}"/>

templates/mybnb/components/search_field.html
<div class="max-w-lg w-full lg:max-w-xs">
    <label for="search" class="sr-only">Search</label>
    <div class="relative">
        <div class="flex flex-col">
            <div class="relative">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                    <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                        fill="currentColor" aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                            clip-rule="evenodd"/>
                    </svg>
                </div>
                <input class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white shadow-sm placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:ring-1 focus:ring-blue-600 focus:border-blue-600 text-xs"
                    type="search"
                    name="query" placeholder="Search for homes"
                    @search="$event.prevent"
                    hx-post="{% url 'mybnb:search' %}"
                    hx-trigger="keyup changed delay:500ms, search"
                    hx-target="#search-results"/>
            </div>
        </div>

    </div>
</div>

templates/mybnb/components/sort.html
<div id="sort" class="relative" x-data="{open: false, active: false}">
    <div>
        <button type="button" class="group inline-flex items-center px-2 py-1.5 border border-gray-300 dark:border-gray-100 shadow
            text-xs font-medium rounded text-gray-800 text-sky-800 dark:text-white bg-white dark:bg-gray-600 hover:bg-gray-50
            dark:hover:bg-gray-800"
            aria-expanded="false"
            :class="open ? 'text-gray-900' : 'text-gray-500'" @click="open = !open">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-1" :class=" active ? 'text-sky-700': ''" fill="none" viewBox="0 0 24 24"
                stroke="currentColor"
                stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 4h13M3 8h9m-9 4h6m4 0l4-4m0 0l4 4m-4-4v12"/>
            </svg>
            <span>Sort</span>
        </button>
    </div>

    <div
        x-transition:enter="transition ease-out duration-300"
        x-transition:enter-start="opacity-0 translate-y-1"
        x-transition:enter-end="opacity-100 translate-y-0"
        x-transition:leave="transition ease-in duration-300"
        x-transition:leave-start="opacity-100 translate-y-0"
        x-transition:leave-end="opacity-0 translate-y-1"
        x-show="open" x-cloak
        class="absolute z-10 left-1/2 transform -translate-x-2/3 mt-3 px-2 w-48 max-w-xs sm:px-0">
        <div
            @click.away="open = false"
            class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden">
            <div class="border-t border-b border-gray-200 divide-y divide-gray-200 bg-white">
                <div class="relative flex items-start py-3 px-2">
                    <div class="mr-3 flex items-center h-5">
                        <input id="price" name="price" value="price:asc" type="checkbox" @change="active = !active"
                            class="focus:ring-indigo-500 h-4 w-4 text-indigo-600 border-gray-300 rounded">
                    </div>
                    <div class="min-w-0 flex-1 text-sm">
                        <label for="price" class="font-medium text-gray-700 select-none">Price </label>
                    </div>
                </div>
            </div>
            <div class="p-1 bg-gray-50">
                <div  class="-m-3 p-3 flex justify-end rounded-md hover:bg-gray-100 transition ease-in-out duration-150">
                    <button type="submit" class="group inline-flex items-center px-2 py-0.5 border border-gray-300 dark:border-gray-100 shadow
                        text-xs font-medium rounded text-gray-800 text-sky-800 dark:text-white bg-white dark:bg-gray-600 hover:bg-sky-500 hover:text-white
                        dark:hover:bg-gray-800"
                        aria-expanded="false"
                        :class="open ? 'text-gray-900' : 'text-gray-500'" @click="open = !open">
                        <span>Apply</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

templates/mybnb/htmx/gallery.html
{% load humanize %}
{% for home in homes %}
    <li class="relative">
        <!--like button-->
        <svg xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6 absolute top-2 right-2 cursor-pointer fill-gray-600 stroke-white" viewBox="0 0 20 20"
            fill="currentColor">
            <path fill-rule="evenodd"
                d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
                clip-rule="evenodd"/>
        </svg>

        <!--Image-->
        <div class="focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-offset-gray-100 focus-within:ring-indigo-500 group block w-full aspect-w-10 aspect-h-7 rounded-lg bg-gray-100 overflow-hidden">
            <div class="h-48 w-full">
                <img src="{{ home.image_url }}" alt="" class="object-cover pointer-events-none group-hover:opacity-75">
            </div>
            <button type="button"
                hx-get="{% url "mybnb:preview" home.id %}"
                hx-target="body"
                hx-swap="beforeend"
                class="absolute inset-0 focus:outline-none z-30" >
                <span class="sr-only">{{ home.address }}</span>
            </button>
        </div>
        <!--Details-->
        <div class="flex justify-between">
            <div class="flex flex-col">
                <p class="mt-2 block text-sm font-medium text-gray-900 truncate pointer-events-none">{{ home.city }}</p>
                <p class="block text-sm font-medium text-gray-500 pointer-events-none">{{ home.country }}</p>
            </div>
            <div class="flex flex-col">
                <p class="mt-2 block text-xs font-semibold text-gray-700 underline truncate pointer-events-none">
                    ${{ home.price|floatformat:"0"|intcomma }} total
                </p>
            </div>
        </div>
        {# infinite scroll only if 20 or more items in search query #}
        {% if forloop.last and total > 19 %}
            <div
                _="on intersection(intersecting)
                    if intersecting remove me then call infiniteScroll()">
            </div>
        {% endif %}
    </li>
{% endfor %}

{# oob response to show search stats under the search button #}
{% if request.htmx %}
    {% include "mybnb/htmx/stats.html" %}
    {% include "mybnb/components/offset.html" %}
{% endif %}

templates/mybnb/htmx/preview.html
{% load humanize %}
<div class="fixed z-50 inset-0 overflow-y-auto" role="dialog" aria-modal="true" id="previewContainer">
    <div class="flex min-h-screen text-center md:block md:px-2 lg:px-4" style="font-size: 0">

        <div
            x-transition:enter="ease-out duration-300"
            x-transition:enter-start="opacity-0 "
            x-transition:enter-end="opacity-100 "
            x-transition:leave="ease-in duration-200"
            x-transition:leave-start="opacity-100"
            x-transition:leave-end="opacity-0"
            class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity md:block" aria-hidden="true"></div>

        <span class="hidden md:inline-block md:align-middle md:h-screen" aria-hidden="true">&#8203;</span>

        <div
            x-transition:enter="ease-out duration-300"
            x-transition:enter-start="opacity-0 translate-y-4 md:translate-y-0 md:scale-95"
            x-transition:enter-end="opacity-100 translate-y-0 md:scale-100"
            x-transition:leave="ease-in duration-200"
            x-transition:leave-start="opacity-100 translate-y-0 md:scale-100"
            x-transition:leave-end="opacity-0 translate-y-4 md:translate-y-0 md:scale-95"
            class="flex text-base text-left transform transition w-full md:inline-block md:max-w-2xl md:px-4 md:my-8 md:align-middle lg:max-w-4xl">
            <div class="w-full relative flex items-center bg-white px-4 pt-14 pb-8 overflow-hidden shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">

                <button type="button"
                    onclick="document.getElementById('previewContainer').remove()"
                    class="absolute top-4 right-4 text-gray-400 hover:text-gray-500 sm:top-8 sm:right-6 md:top-6 md:right-6 lg:top-8 lg:right-8">
                    <span class="sr-only">Close</span>
                    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>

                <div class="w-full grid grid-cols-1 gap-y-8 gap-x-6 items-start sm:grid-cols-12 lg:gap-x-8">
                    <div class="sm:col-span-4 lg:col-span-5">
                        <div class="aspect-w-1 aspect-h-1 rounded-lg bg-gray-100 overflow-hidden">
                            <img src="{{ home.image_url }}" alt="{{ home.address }}" class="object-center object-cover">
                        </div>
                    </div>
                    <div class="sm:col-span-8 lg:col-span-7 flex flex-col h-full">
                        <h2 class="text-2xl font-extrabold text-gray-700 sm:pr-12">{{ home.city }}, {{ home.country }}</h2>
                        <h4 class="text-lg font-semibold text-gray-600 sm:pr-12 mt-2">{{ home.address }}</h4>

                        <section aria-labelledby="information-heading" class="mt-3">
                            <h3 id="information-heading" class="sr-only">Product information</h3>

                            <p class=" text-gray-900">Total Price: ${{ home.price|floatformat:"0"|intcomma }}</p>


                            <div class="mt-6">
                                <h4 class="sr-only">Description</h4>

                                <p class="text-sm text-gray-700">{{ home.description }}</p>
                            </div>
                        </section>

                        <section aria-labelledby="options-heading" class="flex-grow">
                            <h3 id="options-heading" class="sr-only">Actions</h3>

                            <div class="h-full flex items-end justify-end">
                                <div class="mt-6">
                                    <button type="submit" class="w-full bg-sky-600 border border-transparent rounded-md py-3 px-8 flex items-center justify-center text-base font-medium text-white hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-indigo-500">
                                        Book Property
                                    </button>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/mybnb/htmx/stats.html
<span  id="searchStats" hx-swap-oob="true"
    class="text-xs mt-1 text-end inline-flex justify-end px-2 text-gray-600">
    {{ total }} results in {{ processing_time }}ms
</span>

templates/mybnb/search.html
{% extends "base.html" %}

{% block content %}
    <div class="flex flex-col mx-auto container">
        <!--header-->
        <div class="group flex mt-12 pt-2 justify-between bg-slate-100 sticky top-0 z-40">
            {% include "mybnb/components/header.html" %}
            <form id="searchForm" class="flex space-x-2 opacity-100 items-center"
                hx-post="{% url 'mybnb:search' %}"
                hx-target="#search-results"
            >
          
                {% include "mybnb/components/filters.html" %}
                {% include "mybnb/components/offset.html" %}
                {% include "mybnb/components/sort.html" %}
                {% include "mybnb/components/search_field.html" %}
            </form>
        </div>
        <div class="flex justify-end mb-2 bg-slate-100 sticky top-12 z-40">
            {% include "mybnb/htmx/stats.html" %}
        </div>
        <div>
            <p id="indicator" class="htmx-indicator indicator">Working ...</p>
            <p id="seeddb" class="htmx-indicator indicator">Adding properties to your index</p>
            <p id="cleardb" class="htmx-indicator indicator">Clearing all ...</p>
        </div>

        <!--Content-->
        <div class="mx-auto container mt-5">
            <section class="mt-8 pb-16" aria-labelledby="gallery-heading">
                <ul id="search-results" role="list"
                    class="grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 sm:gap-x-6 md:grid-cols-4 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8">
                    {% include "mybnb/htmx/gallery.html" %}
                </ul>
            </section>
        </div>
    </div>
{% endblock %}

{% block footer_js %}
    {{ block.super }}
    <script>
        /**
         * Fetches
         * :) The only js you have to write
         * **/
        function infiniteScroll(){
            const form = document.getElementById("searchForm")
            const formData = new FormData(form)
            // add form values to object
            formData.append('apply_offset', true);
            let data = {}
            formData.forEach(function(value, key){
                data[key] = value;
            });
            // handle multiselect values
            const headers = {
                "X-CSRFToken": "{{ csrf_token }}"
            }
            data.country = formData.getAll('country')
            const context = {
                target:'#search-results', 
                headers: headers,
                swap:'beforeend', values: data
            }
            
            htmx.ajax('POST', "{% url 'mybnb:search' %}", context)
        }
    </script>
{% endblock %}

templates/search_metrics/metrics.html
{% extends "base.html" %}

{% block content %}
    <!--Add htmx headers hear, ca-->
    <div class="flex flex-col mx-auto container">
        <h2 class="font-semibold text-2xl mt-12 text-gray-700">Search Metrics</h2>
        <div class="flex my-3 space-x-2">
            <button hx-post="{% url "search_metrics:seed-db" %}" hx-indicator="#seeddb" hx-target="#tableContainer" hx-swap="outerHTML"
                    class="inline-flex items-center px-1 py-1.5 border border-gray-300 dark:border-gray-100 shadow-sm
                           text-xs font-medium rounded text-gray-700 dark:text-white bg-white dark:bg-gray-600 hover:bg-gray-50
                           dark:hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
                &#10010; Seed DB
            </button>
            <button hx-delete="{% url "search_metrics:clear-db" %}" hx-indicator="#cleardb" hx-target="#tableContainer" hx-swap="outerHTML"
                    class="inline-flex items-center px-1 py-1.5 border border-gray-300 dark:border-gray-100 shadow-sm
                           text-xs font-medium rounded text-gray-700 dark:text-white bg-white dark:bg-gray-600 hover:bg-gray-50
                           dark:hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500">
                &#10007; Clear DB
            </button>
        </div>
        <div>
            <p id="indicator" class="htmx-indicator indicator">Working ...</p>
            <p id="seeddb" class="htmx-indicator indicator">Adding 100,000 records, this will take a minute or less...</p>
            <p id="cleardb" class="htmx-indicator indicator">Clearing all ...</p>
        </div>
        <div class="mx-auto container mt-5">
            {% include "search_metrics/htmx/table.html" %}
        </div>
    </div>
{% endblock %}